react:
  build: ./client/move_with_me
  ports:
    - "3000:3000"
  volumes:
    - ./client/move_with_me:/user/src/app
  links:
    - flask
flask:
  build: ./server
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - ./server:/app
  links:
    - mongodb
mongodb:
  image: mongo:latest
  hostname: mvm_mongodb
  environment:
    - MONGO_INITDB_DATABASE=user_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:27017